version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask_app
    ports:
      - "7000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo  # Se asegura de que MongoDB se inicie antes de Flask
    networks:
      - flask-mongo-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # Expone el puerto 27017 para MongoDB
    volumes:
      - mongo-data:/data/db  # Persistencia de datos
    networks:
      - flask-mongo-network

volumes:
  mongo-data:  # Almacena datos de MongoDB fuera del contenedor

networks:
  flask-mongo-network:
    driver: bridge
