version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask_app
    ports:
      - "7000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo  
    networks:
      - flask-mongo-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  
    volumes:
      - mongo-data:/data/db  
    networks:
      - flask-mongo-network

volumes:
  mongo-data:  

networks:
  flask-mongo-network:
    driver: bridge
